package zxc.iconic.xenon.helpers;

import org.telegram.messenger.SendMessagesHelper;
import org.telegram.messenger.UserConfig;
import org.telegram.tgnet.ConnectionsManager;
import org.telegram.tgnet.TLRPC;
import java.io.File;

/** Sends only a document created by the backup service, using the pinned account identity. */
public final class AutoBackupSender {
    public static File createFile(android.content.Context context, long userId, long timestamp) throws java.io.IOException {
        // The upload layer checks file descriptors too, so app-private files
        // cannot be used even with the direct document sender.
        File directory = context.getExternalFilesDir("auto_backups");
        if (directory == null) throw new java.io.IOException("Backup storage is unavailable");
        if (!directory.isDirectory() && !directory.mkdirs()) throw new java.io.IOException("Cannot create backup directory");
        return new File(directory, "xenon_config_" + userId + "_" + timestamp + ".json");
    }

    public static void send(int account, long userId, File file, String caption) throws java.io.IOException {
        if (account < 0 || account >= UserConfig.MAX_ACCOUNT_COUNT
                || !UserConfig.getInstance(account).isClientActivated()
                || UserConfig.getInstance(account).getClientUserId() != userId) {
            throw new java.io.IOException("Backup account is no longer available");
        }
        if (!file.isFile() || file.length() == 0) throw new java.io.IOException("Empty backup file");
        TLRPC.TL_document document = new TLRPC.TL_document();
        document.file_reference = new byte[0];
        document.date = ConnectionsManager.getInstance(account).getCurrentTime();
        document.mime_type = "application/json";
        document.size = file.length();
        TLRPC.TL_documentAttributeFilename filename = new TLRPC.TL_documentAttributeFilename();
        filename.file_name = file.getName();
        document.attributes.add(filename);
        // The generic attachment picker rejects private app files. This document
        // is generated by us and can go straight to Telegram's upload pipeline.
        SendMessagesHelper.getInstance(account).sendMessage(SendMessagesHelper.SendMessageParams.of(
                document, null, file.getAbsolutePath(), userId, null, null, caption,
                null, null, null, false, 0, 0, 0, null, null, false));
    }
}
